"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var readlineSync = require("readline-sync");
var Numerito = readlineSync.questionInt("\nQue numero de mes quieres? ");
var NumeroMeses = new Array(13);
NumeroMeses[0] = "Enero";
NumeroMeses[1] = "febrero";
NumeroMeses[2] = "marzo";
NumeroMeses[3] = "Abril";
NumeroMeses[4] = "Mayo";
NumeroMeses[5] = "Junio";
NumeroMeses[6] = "Julio";
NumeroMeses[7] = "Agosto";
NumeroMeses[8] = "Septiembre";
NumeroMeses[9] = "Octubre";
NumeroMeses[10] = "Noviembre";
NumeroMeses[11] = "Diciembre";
var indice = Numerito - 1;
console.log(NumeroMeses[indice] + "\n");
